"""Compatibility wrapper for `pyinkcli.packages.ink.dom`."""

from pyinkcli.packages.ink.dom import (
    DOMElement,
    DOMNode,
    DOMNodeAttribute,
    ElementNames,
    NodeNames,
    TextNode,
    addLayoutListener,
    appendChildNode,
    createNode,
    createTextNode,
    emitLayoutListeners,
    insertBeforeNode,
    removeChildNode,
    setAttribute,
    setStyle,
    setTextNodeValue,
    squashTextNodes,
)

__all__ = [
    "DOMElement",
    "TextNode",
    "DOMNode",
    "DOMNodeAttribute",
    "ElementNames",
    "NodeNames",
    "createNode",
    "appendChildNode",
    "insertBeforeNode",
    "removeChildNode",
    "setAttribute",
    "setStyle",
    "createTextNode",
    "setTextNodeValue",
    "addLayoutListener",
    "emitLayoutListeners",
    "squashTextNodes",
]
