"""Terminal host surface for the renderer layer analogous to react-dom host internals."""

from pyinkcli.packages.ink.dom import (
    AccessibilityInfo,
    DOMElement,
    DOMNode,
    DOMNodeAttribute,
    ElementName,
    ElementNames,
    NodeName,
    NodeNames,
    TextNode,
    addLayoutListener,
    appendChildNode,
    createNode,
    createTextNode,
    emitLayoutListeners,
    insertBeforeNode,
    removeChildNode,
    setAttribute,
    setStyle,
    setTextNodeValue,
    squashTextNodes,
)
from pyinkcli.packages.ink.styles import Styles, TextWrap, apply_styles

__all__ = [
    "AccessibilityInfo",
    "DOMElement",
    "DOMNode",
    "DOMNodeAttribute",
    "ElementName",
    "ElementNames",
    "NodeName",
    "NodeNames",
    "Styles",
    "TextNode",
    "TextWrap",
    "addLayoutListener",
    "appendChildNode",
    "apply_styles",
    "createNode",
    "createTextNode",
    "emitLayoutListeners",
    "insertBeforeNode",
    "removeChildNode",
    "setAttribute",
    "setStyle",
    "setTextNodeValue",
    "squashTextNodes",
]
